<a href="https://colab.research.google.com/github/Viktoriia-code26/goit-ds-hw-01/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
## Task 1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

import numpy as np
a = np.arange(1, 11)
print(a)



[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
## Task 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

a = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
print(a)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
## Task 3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

a = np.random.randint(1, 11, size=(5, 5))
print(a)

[[ 3  4  1  2  1]
 [ 9  2  8  9  8]
 [10  2  2  3  3]
 [10  3  5  4  1]
 [ 4  9  9  4  1]]


In [5]:
## Task 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
a = np.random.random((4, 4))
print(a)


[[0.23715945 0.42483444 0.76597854 0.01266962]
 [0.69881895 0.82637851 0.94014361 0.20581313]
 [0.2791868  0.93504006 0.98002047 0.75987992]
 [0.79029297 0.34842742 0.88207991 0.80344822]]


In [6]:
## Task 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(1, 11, size=(5, 5))
b = np.random.randint(1, 11, size=(5, 5))
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)



[[ 6  5  6  1  5]
 [10  7  9  4  4]
 [ 9 10  3  2  4]
 [ 5  3  4  9  9]
 [ 3  1 10  6  8]]
[[ 3  3  2  5  3]
 [ 6  7  2  6  3]
 [ 3 10 10 10  3]
 [ 4  7  2  2  8]
 [ 5  2  4  4  6]]
[[ 9  8  8  6  8]
 [16 14 11 10  7]
 [12 20 13 12  7]
 [ 9 10  6 11 17]
 [ 8  3 14 10 14]]
[[ 3  2  4 -4  2]
 [ 4  0  7 -2  1]
 [ 6  0 -7 -8  1]
 [ 1 -4  2  7  1]
 [-2 -1  6  2  2]]
[[ 18  15  12   5  15]
 [ 60  49  18  24  12]
 [ 27 100  30  20  12]
 [ 20  21   8  18  72]
 [ 15   2  40  24  48]]


In [7]:
## Task 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
a = np.random.random((7))
b = np.random.random((7))
print(a)
print(b)
print(np.dot(a, b))

[0.6931732  0.14927524 0.14162352 0.11761773 0.79690823 0.50486868
 0.14586745]
[0.16257185 0.55297721 0.19097753 0.65965767 0.68617134 0.14428048
 0.48200847]
0.9898382343962254


In [8]:
## Task 7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
c = np.dot(a, b)
print(a)
print(b)
print(c)


[[5 2]
 [4 7]]
[[5 7 1]
 [7 7 8]]
[[39 49 21]
 [69 77 60]]


In [9]:
## Task 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
a = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)


[[ 1  3 10]
 [ 1  4  3]
 [ 4  4  9]]
[[-0.27586207 -0.14942529  0.35632184]
 [-0.03448276  0.35632184 -0.08045977]
 [ 0.13793103 -0.09195402 -0.01149425]]


In [10]:
## Task 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
a = np.random.random((4, 4))
print(a)
b = a.T
print(b)

[[0.4805904  0.64865494 0.98983246 0.53426753]
 [0.54021798 0.81502165 0.92744255 0.3647001 ]
 [0.61538651 0.3902471  0.13807697 0.36812229]
 [0.34947845 0.54233652 0.7659062  0.99286951]]
[[0.4805904  0.54021798 0.61538651 0.34947845]
 [0.64865494 0.81502165 0.3902471  0.54233652]
 [0.98983246 0.92744255 0.13807697 0.7659062 ]
 [0.53426753 0.3647001  0.36812229 0.99286951]]


In [11]:
## Task 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
print(a)
print(b)
print(np.dot(a, b))


[[ 6  4  1 10]
 [ 5  7 10  7]
 [ 2  1  8  2]]
[10  6  6 10]
[190 222  94]


In [12]:
## Task 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
a = np.random.random((2, 3))
b = np.random.random(3)
print(a)
print(b)
print(np.dot(a, b))

[[0.67622705 0.02383672 0.09633637]
 [0.29309137 0.99757201 0.32814812]]
[0.16637149 0.25786249 0.20141526]
[0.13805511 0.37209249]


In [13]:
## Task 12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a)
print(b)
print(a * b)

[[ 2 10]
 [10  4]]
[[1 1]
 [2 7]]
[[ 2 10]
 [20 28]]


In [14]:
## Task 13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a)
print(b)
print(np.dot(a, b))

[[10  1]
 [ 4  9]]
[[ 7  4]
 [ 9 10]]
[[ 79  50]
 [109 106]]


In [15]:
## Task 14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
a = np.random.randint(1, 101, size=(5, 5))
print(a)
print(np.sum(a))


[[61 65 20 68 12]
 [72 75 65 22 17]
 [29 13 30 98 74]
 [24 72 38 36 78]
 [11 79 23 99 58]]
1239


In [16]:
## Task 15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print(a)
print(b)
print(a - b)

[[ 6  1  2  2]
 [ 8 10  8  3]
 [ 9  2  9  7]
 [ 5  6  8  4]]
[[ 8  6  3  1]
 [ 9  5  7  5]
 [ 9 10  6  3]
 [ 9  9 10  1]]
[[-2 -5 -1  1]
 [-1  5  1 -2]
 [ 0 -8  3  4]
 [-4 -3 -2  3]]


In [17]:
## Task 16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
a = np.random.random((3, 3))
print(a)
row_sums = np.sum(a, axis=1).reshape(3, 1)
print(row_sums)


[[0.36955401 0.4691688  0.86350476]
 [0.12693822 0.79325688 0.30793286]
 [0.07031973 0.74916367 0.6940453 ]]
[[1.70222757]
 [1.22812796]
 [1.5135287 ]]


In [18]:
## Task 17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
a = np.random.randint(1, 11, size=(3, 4))
print(a)
b = np.square(a)
print(b)

[[ 4  2  8  6]
 [ 1  4 10  4]
 [ 4  5  9  4]]
[[ 16   4  64  36]
 [  1  16 100  16]
 [ 16  25  81  16]]


In [19]:
## Task 18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
a = np.random.randint(1, 51, size=4)
print(a)
b = np.sqrt(a)
c = np.round(b, 2)
print(b)
print(c)


[33 50 35 50]
[5.74456265 7.07106781 5.91607978 7.07106781]
[5.74 7.07 5.92 7.07]


Завдання 2

In [20]:
## Task 1  Замініть усі непарні числа в arr на -1
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [21]:
## Task 2 Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a2 = a.reshape(2, 5)
print(a)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
## Task 3 Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
b = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
c = np.vstack((a, b))
print(c)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [23]:
## Task 4 Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

##Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1, 2, 3])
b = np.repeat(a, 3)
c = np.tile(a, 3)
d = np.concatenate((b, c[1:]))
print(d)



[1 1 1 2 2 2 3 3 3 2 3 1 2 3 1 2 3]


In [24]:
## Task 5 Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a, b)
print(c)

[2 4]


In [25]:
## Task 6 Отримайте позиції перших 5 максимальних значень у заданому масиві a
a = np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
b = np.sort(a)
print(b[-5:])

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


In [26]:
## Task 7 Вилучіть усі значення NaN із одновимірного масиву

a =np.array([1,2,3,np.nan,5,6,7,np.nan])
b  = a[np.isnan(a) == False]
print(b)

[1. 2. 3. 5. 6. 7.]


In [27]:
## Task 8 Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])


distance = np.sqrt(np.sum((a - b) ** 2))

print(distance)

6.708203932499369


In [28]:
## Task 9  Знайдіть індекс 5-го повторення числа 1 у масиві x
import numpy as np
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
c = np.where(x == 1)[0]
print(c[4])

8


In [29]:
## Task 10  Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

# Input np.random.seed(100) a = np.random.randint(0, 5, 10)

## [0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

np.random.seed(100)
a = np.random.randint(0, 5, 10)

seen = set()
result = []

for x in a:
    if x in seen:
        result.append(True)
    else:
        result.append(False)
        seen.add(x)

result = np.array(result)

print(a)
print(result)



[0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]
